{{- if .Values.twistlock.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.twistlock "name" "twistlock" "defaults" (include "bigbang.defaults.twistlock" .)) }}
{{- end }}

{{- define "bigbang.defaults.twistlock" -}}
# hostname is deprecated and replaced with domain. But if hostname exists then use it.
{{- $domainName := default .Values.domain .Values.hostname }}
hostname: {{ $domainName }}
domain: {{ $domainName }}

openshift: {{ .Values.openshift }}

prometheus:
  servicemonitor:
    enabled: {{ .Values.monitoring.enabled }}

imagePullSecrets:
- name: private-registry

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  ingressLabels:
    {{- $gateway := default "public" .Values.twistlock.ingress.gateway }}
    {{- $default := dict "app" (dig "gateways" $gateway "ingressGateway" nil .Values.istio) "istio" nil }}
    {{- toYaml (dig "values" "gateways" $gateway "selector" $default .Values.istio) | nindent 4 }}
  nodeCidr: {{ .Values.networkPolicies.nodeCidr }}

istio:
  enabled: {{ .Values.istio.enabled }}
  console:
    gateways:
    - istio-system/{{ default "public" .Values.twistlock.ingress.gateway }}

{{- if .Values.istio.enabled }}
annotations:
  {{- if .Values.istio.git.semver }}
  bigbang.dev/istioVersion: {{ .Values.istio.git.semver | trimSuffix (regexFind "-bb.*" .Values.istio.git.semver) }}
  {{- else if .Values.istio.git.tag }}
  bigbang.dev/istioVersion: {{ .Values.istio.git.tag | trimSuffix (regexFind "-bb.*" .Values.istio.git.tag) }}
  {{- else if .Values.istio.git.branch }}
  bigbang.dev/istioVersion: {{ .Values.istio.git.branch }}
  {{- end }}
{{- end }}

console:
  image:
    imagePullPolicy: {{ .Values.imagePullPolicy }}

{{- end -}}
