include:
  - project: 'platform-one/big-bang/pipeline-templates/pipeline-templates'
    ref: BrandenCobb-master-patch-03894
    file: '/pipelines/bigbang.yaml'
variables:
  PIPELINE_REPO_BRANCH: BrandenCobb-master-patch-03894
  DEBUG_ENABLED: "true"
