include:
  - project: 'platform-one/big-bang/pipeline-templates/pipeline-templates'
    ref: 23-pluto-ver-bump
    file: '/pipelines/bigbang.yaml'
variables:
  PIPELINE_REPO_BRANCH: 23-pluto-ver-bump
  DEBUG_ENABLED: true
