{{- if .Values.addons.gitlabRunner.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.addons.gitlabRunner "name" "gitlab-runner" "defaults" (include "bigbang.defaults.gitlab-runner" .)) }}
{{- end }}

{{- define "bigbang.defaults.gitlab-runner" -}}

imagePullPolicy: {{ .Values.imagePullPolicy }}

imagePullSecrets:
- name: private-registry

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}

# no longer necessary to pass through monitoring toggle
# the package chart uses: .Capabilities.APIVersions.Has "monitoring.coreos.com/v1"
# monitoring:
#   enabled: {{ .Values.monitoring.enabled }}

# When istio injected, add an annotation with the istio version to the manager pods only
{{- if (and (eq (dig "istio" "injection" "enabled" .Values.addons.gitlab) "enabled") .Values.istio.enabled) }}
podAnnotations:
  {{ include "istioAnnotation" . }}
{{- end }}

{{- end -}}
