{{- if .Values.podinfo.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.podinfo "name" "podinfo" "defaults" (include "bigbang.defaults.podinfo" .)) }}
{{- end }}

{{- define "bigbang.defaults.podinfo" -}}
replicaCount: 3

image:
  pullSecrets:
  - name: private-registry
  pullPolicy: {{ .Values.imagePullPolicy }}

openshift: {{ .Values.openshift }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

serviceMonitor:
  enabled: {{ .Values.monitoring.enabled }}
  dashboards:
    namespace: monitoring

istio:
  enabled: {{ .Values.istio.enabled }}
{{- end -}}
