{{- if .Values.istio.enabled }}

{{/*
For backwards compatibility, get key/cert from .Values.istio.ingress
*/}}
{{- $default := .Values.istio.ingress | default dict -}}

{{- range $name, $values := .Values.istio.gateways }}
{{- range $index, $servervalues := $values.servers }}
{{- if or (and (dig "tls" "cert" "" $servervalues) (dig "tls" "key" "" $servervalues)) (and $default.cert $default.key) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s-cert" $index $name }}
  namespace: istio-system
  labels:
    app.kubernetes.io/name: istio-controlplane
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" $ | nindent 4}}
type: kubernetes.io/tls
data:
  tls.crt: {{ default $default.cert $servervalues.tls.cert | b64enc }}
  tls.key: {{ default $default.key $servervalues.tls.key | b64enc }}
---
{{- end }}
{{- end }}
{{- end }}

{{- end }}
