{{- if or ( eq .Values.addons.metricsServer.enabled "true") (eq .Values.addons.metricsServer.enabled "auto") }}
{{- if or (not (.Capabilities.APIVersions.Has "metrics.k8s.io/v1beta1")) (lookup "helm.toolkit.fluxcd.io/v2beta1" "HelmRelease" "bigbang" "metrics-server") }}
apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: metrics-server
    app.kubernetes.io/component: "cluster-utilities"
    {{- include "commonLabels" . | nindent 4}}
    istio-injection: {{ dig "istio" "injection" "enabled" .Values.addons.metricsServer }}
  name: metrics-server
{{- end }}
{{- end }}